version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - REPOSITORY_URI=public.ecr.aws/u0f0p0q3/ci-cd-demo
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      # Build all services
      - SERVICES=("CI-CD-Demo" "CartService" "EmailService" "OrderService" "PaymentService" "ProductCatalogService" "ServiceDiscovery" "UserService")
      - for SERVICE in ${SERVICES[@]}; do
          cd $SERVICE;
          mvn clean install;
          cd ..;
        done

  build:
    commands:
      - echo Build started on `date`
      # Build Docker images for all services
      - for SERVICE in ${SERVICES[@]}; do
          echo Building Docker image for $SERVICE;
          docker build -t $REPOSITORY_URI:$SERVICE-latest ./$SERVICE;
          docker tag $REPOSITORY_URI:$SERVICE-latest $REPOSITORY_URI:$SERVICE-$IMAGE_TAG;
        done

  post_build:
    commands:
      - echo Build completed on `date`
      # Push Docker images for all services
      - for SERVICE in ${SERVICES[@]}; do
          echo Pushing Docker images for $SERVICE;
          docker push $REPOSITORY_URI:$SERVICE-latest;
          docker push $REPOSITORY_URI:$SERVICE-$IMAGE_TAG;
          printf '[{"name":"%s","imageUri":"%s"}]' $SERVICE $REPOSITORY_URI:$SERVICE-$IMAGE_TAG > ./$SERVICE/imagedefinitions.json;
          echo $SERVICE;
          echo printing imagedefinitions.json for $SERVICE;
          cat ./$SERVICE/imagedefinitions.json;
        done

artifacts:
  files:
    - '**/appspec.yml'
    - '**/scripts/**'
    - '**/target/*.jar'
    - '**/imagedefinitions.json'